version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "serverless-saas-lab1"
s3_bucket = "saas-zwy"
s3_prefix = "serverless-saas-lab1"
region = "us-east-2"
confirm_changeset = false
capabilities = "CAPABILITY_NAMED_IAM"
